### ISSUE TITLE
Aniworld-Downloader fails to run for me

### ISSUE THREAD

**Issue by MikaHD666** [phoenixthrush/AniWorld-Downloader#12]
Like the title says, aniworld-downloader doesn't respond neither using the interactive mode nor with command line arguments

I tried cloning the project to see what the error is and this came up:

```
Exception has occurred: CalledProcessError
Command '['aniworld', '--episode', 'https://aniworld.to/anime/stream/demon-slayer-kimetsu-no-yaiba/staffel-1/episode-1', '--action', 'Watch', '--output', 'C:\\Users\\***\\Downloads', '--language', 'German Dub', '--provider', 'VOE', '--only-command']' returned non-zero exit status 1.
  File "C:\Users\***\OneDrive\Desktop\Aniworld_downloader_local\aniworld\tests\test_aniworld.py", line 62, in test_main
    result = subprocess.run(
             ^^^^^^^^^^^^^^^
  File "C:\Users\***\OneDrive\Desktop\Aniworld_downloader_local\aniworld\tests\test_aniworld.py", line 80, in run_test
    output = test_main(args)
  File "C:\Users\***\OneDrive\Desktop\Aniworld_downloader_local\aniworld\tests\test_aniworld.py", line 106, in test_functions
    run_test(
  File "C:\Users\***\OneDrive\Desktop\Aniworld_downloader_local\aniworld\tests\test_aniworld.py", line 139, in <module>
    test_functions()
subprocess.CalledProcessError: Command '['aniworld', '--episode', 'https://aniworld.to/anime/stream/demon-slayer-kimetsu-no-yaiba/staffel-1/episode-1', '--action', 'Watch', '--output', 'C:\\Users\\mikah\\Downloads', '--language', 'German Dub', '--provider', 'VOE', '--only-command']' returned non-zero exit status 1.
```

Version used is 2.1.5
Python Version used is 3.11.6 (I'm thinking that this is the issue, but i haven't changed anything with my system before or after the error appeared...)

**Comment by phoenixthrush** [comment]
Hi,

I tested the command on MacOS and it works fine for me.
Could you try running aniworld with the --debug flag appended?

After that you can run this in a new PowerShell window:
Get-Content -Wait $env:TEMP\aniworld.log

It might be crashing because German Dub isn't quoted, but I'm not entirely sure.

Could you paste your log file here?

**Comment by MikaHD666** [comment]
Output for "aniworld --debug":

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\mikah\AppData\Local\Programs\Python\Python311\Scripts\aniworld.exe\__main__.py", line 7, in <module>  
  File "C:\Users\mikah\OneDrive\Desktop\Aniworld_downloader_local\aniworld\src\aniworld\__main__.py", line 505, in main
    args = parse_arguments()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\mikah\OneDrive\Desktop\Aniworld_downloader_local\aniworld\src\aniworld\__main__.py", line 434, in parse_arguments
    subprocess.run(command, check=True)
  File "C:\Users\mikah\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mikah\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\mikah\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
```

**Comment by phoenixthrush** [comment]
Hi, I just fixed that bug, thanks for reporting it!
Could you try running it again using --debug?
Make sure to pull the latest changes and reinstall the dev version before testing.

**Comment by MikaHD666** [comment]
[log.txt](https://github.com/user-attachments/files/17447268/log.txt)
I pulled the latest dev build with 
`pip install --upgrade git+https://github.com/phoenixthrush/AniWorld-Downloader.git#egg=aniworld`
The last reaction from aniworld was a request timeout from aniworld

**Comment by phoenixthrush** [comment]
Yeah this has been happening for a few days, the only thing I can think of now is to use a VPN and it will go through, I could spend some time using Playwright or another way to do these url fetches that uses a headless browser which will probably work too. But for now you could use a VPN.

**Comment by MikaHD666** [comment]
Good to know that it's an aniworld issue and not an issue with your project.
Thanks for the quick responses!
