### ISSUE TITLE
doesn't work for me on Windows 10 64 bit

### ISSUE THREAD

**Issue by AndiJN** [phoenixthrush/AniWorld-Downloader#14]
aniworld
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Andreas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\Scripts\aniworld.exe\__main__.py", line 4, in <module>
    from aniworld.__main__ import main
  File "C:\Users\Andreas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\aniworld\__main__.py", line 12, in <module>
    import curses
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.240.0_x64__qbz5n2kfra8p0\Lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'

**Comment by phoenixthrush** [comment]
Hi,

The windows-curses module isn't available for Python 3.13 yet.
You can install Python 3.12 and try to install aniworld again.

https://www.python.org/ftp/python/3.12.7/python-3.12.7-amd64.exe
https://pypi.org/project/windows-curses/#files

**Comment by AndiJN** [comment]
thanks, that helped me

**Comment by phoenixthrush** [comment]
I got the same issue after trying to install aniworld on my ARM machine. Just uninstall all ARM Python versions, install [the AMD64 version](https://www.python.org/ftp/python/3.12.9/python-3.12.9-amd64.exe), and then reinstall aniworld.
