### ISSUE TITLE
"Display not Found" via Command

### ISSUE THREAD

**Issue by YozouChan** [phoenixthrush/AniWorld-Downloader#28]
Hello,
i'm trying to use AniWorld-Downloader on a LXC as a downloader for anime.
If i'm using the ui with the "aniworld" command, i'm able to download anime flawless... But when i'm trying to download an anime via console i'm getting an error like the following is showing:

```shell
root@test12345:~# aniworld --episode https://aniworld.to/anime/stream/demon-slayer-kimetsu-no-yaiba/staffel-1/episode-1 --action Download --debug
# Failed to parse arguments: Cannot open display: 
Traceback (most recent call last):
  File "/usr/local/bin/aniworld", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aniworld/__main__.py", line 773, in main
    execute_with_params(args, selected_episodes, anime_title, language, anime_slug=slug)
  File "/usr/local/lib/python3.12/dist-packages/aniworld/__main__.py", line 873, in execute_with_params
    execute(params=params)
  File "/usr/local/lib/python3.12/dist-packages/aniworld/execute.py", line 433, in execute
    process_episode({
  File "/usr/local/lib/python3.12/dist-packages/aniworld/execute.py", line 469, in process_episode
    process_provider({
  File "/usr/local/lib/python3.12/dist-packages/aniworld/execute.py", line 540, in process_provider
    perform_action(episode_params)
  File "/usr/local/lib/python3.12/dist-packages/aniworld/execute.py", line 291, in perform_action
    handle_download_action(params)
  File "/usr/local/lib/python3.12/dist-packages/aniworld/execute.py", line 362, in handle_download_action
    file_path = os.path.join(
                ^^^^^^^^^^^^^
  File "<frozen posixpath>", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType
``` 

I've also tried to specify an output directory or using --episode-file instead, with no success.
Why is downloading via ui (aniworld command) possible but not via command. Am i doing anything wrong? 😅
Thank you in advance! 💕

**Comment by phoenixthrush** [comment]
Hi, you aren't doing anything wrong, we also get this now. Going to fix this in a bit. :)

**Comment by YozouChan** [comment]
Okie, thank you pretty much for the help AND doing such a nice project and also sharing it with everyone 💕

**Comment by phoenixthrush** [comment]
Fixed. :)

**Comment by Tmaster055** [comment]
Hi, the issue of the double path in the menu should be fixed! (:

**Comment by Tmaster055** [comment]
Hi, the double path when using the menu should now be fixed! (:
