### ISSUE TITLE
Anime Wont download

### ISSUE THREAD

**Issue by GamingKatze153** [phoenixthrush/AniWorld-Downloader#4]
I tried downloading Jojo bizzare adventuer 2012 S01E01 but after the download begins it says removed empty download directory   C:/Users/name/Downloads/Jojos Bizarre Adventure

**Comment by phoenixthrush** [comment]
Hi, do you have yt-dlp in path, it should be checked on startup but maybe that could be the reason?
I tried to download the mentioned episode with all three languages and it went through.
It could be that your IP is being blocked due to a captcha, I have a check for this but it could still be that you are being blocked.
Can you try the "watch" option? You need mpv in the path.
Also check that you are running the latest version, as I am currently working on it.

**Comment by GamingKatze153** [comment]
So i checked an i had mpv and yt-dlp in PATH, after updating (over  pip install -U aniworld) there is a new error 

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\name\AppData\Local\Programs\Python\Python312\Scripts\aniworld.exe\__main__.py", line 7, in <module>
  File "C:\Users\name\AppData\Local\Programs\Python\Python312\Lib\site-packages\aniworld\__main__.py", line 376, in main
    app.run()
  File "C:\Users\name\AppData\Local\Programs\Python\Python312\Lib\site-packages\npyscreen\apNPSApplication.py", line 30, in run
    return npyssafewrapper.wrapper(self.__remove_argument_call_main)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\name\AppData\Local\Programs\Python\Python312\Lib\site-packages\npyscreen\npyssafewrapper.py", line 41, in wrapper
    wrapper_no_fork(call_function)
  File "C:\Users\name\AppData\Local\Programs\Python\Python312\Lib\site-packages\npyscreen\npyssafewrapper.py", line 97, in wrapper_no_fork
    return_code = call_function(_SCREEN)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\name\AppData\Local\Programs\Python\Python312\Lib\site-packages\npyscreen\apNPSApplication.py", line 25, in __remove_argument_call_main
    return self.main()
           ^^^^^^^^^^^
  File "C:\Users\name\AppData\Local\Programs\Python\Python312\Lib\site-packages\npyscreen\apNPSApplicationManaged.py", line 172, in main
    self._THISFORM.edit()
  File "C:\Users\name\AppData\Local\Programs\Python\Python312\Lib\site-packages\npyscreen\fmActionForm.py", line 77, in edit
    self.edit_return_value = self.on_ok()
                             ^^^^^^^^^^^^
  File "C:\Users\name\AppData\Local\Programs\Python\Python312\Lib\site-packages\aniworld\__main__.py", line 328, in on_ok
    copy(source_path, destination_path)
  File "C:\Users\name\AppData\Local\Programs\Python\Python312\Lib\shutil.py", line 435, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\name\AppData\Local\Programs\Python\Python312\Lib\shutil.py", line 260, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\name\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\aniworld\\skip.lua'

Also there is not a directory in lib thats name is aniworld
i tried other anime these also aren't function

**Comment by phoenixthrush** [comment]
Hi, can you just create this folder if needed and add the file to the path to check if it's just that?

https://raw.githubusercontent.com/phoenixthrush/AniWorld-Downloader/module/src/aniworld/skip.lua

To

C:\Users\name\AppData\Local\Programs\Python\Python312\Lib\site-packages\aniworld\skip.lua

**Comment by GamingKatze153** [comment]
After doing what you said it says

Downloading 'C:\Users\name\Downloads\Jojos Bizarre Adventure/Jojos Bizarre Adventure - S1E1'
Removed empty directory: C:\Users\name\Downloads\Jojos Bizarre Adventure

I also changed the directory to a folder in c drive but its says the same

**Comment by phoenixthrush** [comment]
I just realised that you are on windows lol, I havent tested windows yet because of the npyscreen library. Does the selection window work where you can choose language and provider and so on? It removes the download directory probably because of the slash. Windows uses backslashes and macos and linux use forward slashes, so it can't download to the specified directory. Also, I just made a change to include the skip.lua file in the package.

**Comment by phoenixthrush** [comment]
Hi, download should be working now, please update. Watching still seems to be broken, but I'll check tomorrow.

**Comment by phoenixthrush** [comment]
Remember to select VOE from the provider menu to get better download speeds.

**Comment by GamingKatze153** [comment]
Thanks for the good Support everything functions now

**Comment by phoenixthrush** [comment]
Awesome, I'll add watch support for Windows next.

Please star this project, which would make my day if you like it.
